/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Alimentos.Alimento;
import Ejercicios.Ejercicio;
import Interfaz.Controladores.ControladorAlimentos;
import Interfaz.Controladores.ControladorEjercicios;
import Interfaz.Controladores.ControladorPersona;
import Personas.Administrador;
import Personas.Usuario;
import java.io.File;
import java.util.Scanner;

/**
 *
 * @author corre
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public static void mensajeAlerta(String mensaje,String titulo){
        javax.swing.JOptionPane.showMessageDialog(null,mensaje , titulo, javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }    
    
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(this);
        Usuario u;
        Administrador ad;
        Alimento a;
        Ejercicio ej;
        String[] datos;
        
        try(Scanner scFile = new Scanner(new File("./Usuarios.csv"))){
            while(scFile.hasNextLine()){
                datos = scFile.nextLine().split(",");
                u = new Usuario(Double.parseDouble(datos[0]),Double.parseDouble(datos[1]),datos[2],datos[3],datos[4],datos[5],datos[6],Integer.parseInt(datos[7]));
                ControladorPersona.uss.add(u);
            }
        }catch(Exception e){
            mensajeAlerta("No se ha encontrado el documento","Registro");
        }
        
        try(Scanner scFile = new Scanner(new File("./Administradores.csv"))){
            while(scFile.hasNextLine()){
                datos = scFile.nextLine().split(",");
                ad = new Administrador(Integer.parseInt(datos[0]),datos[1],datos[2],datos[3],datos[4],datos[5],datos[6],Integer.parseInt(datos[7]));
                ControladorPersona.adm.add(ad);
            }
        }catch(Exception e){
            mensajeAlerta("No se ha encontrado el documento","Registro");
        }        
   
        try(Scanner scFile = new Scanner(new File("./Alimentos.csv"))){
            while(scFile.hasNextLine()){
                datos = scFile.nextLine().split(",");
                a = new Alimento(datos[0],Double.parseDouble(datos[1]),datos[2],datos[3],datos[4]);
                ControladorAlimentos.alimentos.add(a);
            }
        }catch(Exception e){
            mensajeAlerta("No se ha encontrado el documento","Registro");
        }        
     
        try(Scanner scFile = new Scanner(new File("./Ejercicios.csv"))){
            while(scFile.hasNextLine()){
                datos = scFile.nextLine().split(",");
                ej = new Ejercicio(datos[0],Double.parseDouble(datos[1]),datos[2],datos[3],datos[4]);
                ControladorEjercicios.ejercicios.add(ej);
            }
        }catch(Exception e){
            mensajeAlerta("No se ha encontrado el documento","Registro");
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuarioButton = new javax.swing.JButton();
        adminButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usuarioButton.setText("Usuario");
        usuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioButtonActionPerformed(evt);
            }
        });

        adminButton.setText("Administrador");
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(225, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(205, 205, 205))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(usuarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioButtonActionPerformed
        InicioUsuario iu = new InicioUsuario();
        iu.setVisible(true);
    }//GEN-LAST:event_usuarioButtonActionPerformed

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        InicioAdministrador ia = new InicioAdministrador();
        ia.setVisible(true);
    }//GEN-LAST:event_adminButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminButton;
    private javax.swing.JButton usuarioButton;
    // End of variables declaration//GEN-END:variables
}
