/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Interfaz.Controladores.ControladorPersona;
import Personas.Usuario;
import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;

/**
 *
 * @author corre
 */
public class ListaPorEstado extends javax.swing.JFrame {
    /**
     * Creates new form ListaPorEstado
     */
    public ListaPorEstado() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        bajoPesoButton = new javax.swing.JButton();
        obesidad1Button = new javax.swing.JButton();
        obesidad3Button = new javax.swing.JButton();
        SobrePesoButton = new javax.swing.JButton();
        saludableButton = new javax.swing.JButton();
        obesidad2Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton3.setText("Atras");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        bajoPesoButton.setText("Lista estado Bajo Peso");
        bajoPesoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajoPesoButtonActionPerformed(evt);
            }
        });

        obesidad1Button.setText("Lista estado Obesidad clase 1");
        obesidad1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obesidad1ButtonActionPerformed(evt);
            }
        });

        obesidad3Button.setText("Lista estado Obesidad clase 3");
        obesidad3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obesidad3ButtonActionPerformed(evt);
            }
        });

        SobrePesoButton.setText("Lista estado Sobre peso");
        SobrePesoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobrePesoButtonActionPerformed(evt);
            }
        });

        saludableButton.setText("Lista estado Saludable");
        saludableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saludableButtonActionPerformed(evt);
            }
        });

        obesidad2Button.setText("Lista estado Obesidad clase 2");
        obesidad2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obesidad2ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SobrePesoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saludableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bajoPesoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(obesidad3Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(obesidad2Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(250, 250, 250))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(obesidad1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(obesidad1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bajoPesoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saludableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obesidad2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SobrePesoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obesidad3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    public static void mensajeAlerta(String mensaje,String titulo){
        javax.swing.JOptionPane.showMessageDialog(null,mensaje , titulo, javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void bajoPesoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajoPesoButtonActionPerformed
        ArrayList<Usuario> usuario =new ArrayList<>();
        for(Usuario u: ControladorPersona.uss)
            if("Bajo peso".equals(u.getEstado()))
                usuario.add(u);
        File f = new File("./ListaUsuariosBajoPeso.csv");
        try(FileWriter fw = new FileWriter(f)){
            for(Usuario u: usuario)
                fw.write(u.toCSV()+"\n");
        } catch(Exception e){
            mensajeAlerta("No se ha encontrado el docuento","Registro");
        }
        mensajeAlerta("Se ha creado un documento con el nonbre 'ListaUsuariosBajoPeso' en la direecion /documentos/neatbeans/proyecto con la lista solicitada","Listado");
    }//GEN-LAST:event_bajoPesoButtonActionPerformed

    private void saludableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saludableButtonActionPerformed
        ArrayList<Usuario> usuario =new ArrayList<>();
        for(Usuario u: ControladorPersona.uss)
            if("Saludable".equals(u.getEstado()))
                usuario.add(u);
        File f = new File("./ListaUsuariosSaludable.csv");
        try(FileWriter fw = new FileWriter(f)){
            for(Usuario u: usuario)
                fw.write(u.toCSV()+"\n");
        } catch(Exception e){
            mensajeAlerta("No se ha encontrado el docuento","Registro");
        }
        mensajeAlerta("Se ha creado un documento con el nonbre 'ListaUsuariosSaludable' en la direecion /documentos/neatbeans/proyecto con la lista solicitada","Listado");
    }//GEN-LAST:event_saludableButtonActionPerformed

    private void SobrePesoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobrePesoButtonActionPerformed
        ArrayList<Usuario> usuario =new ArrayList<>();
        for(Usuario u: ControladorPersona.uss)
            if("Sobre peso".equals(u.getEstado()))
                usuario.add(u);
        File f = new File("./ListaUsuariosSobrePeso.csv");
        try(FileWriter fw = new FileWriter(f)){
            for(Usuario u: usuario)
                fw.write(u.toCSV()+"\n");
        } catch(Exception e){
            mensajeAlerta("No se ha encontrado el docuento","Registro");
        } 
        mensajeAlerta("Se ha creado un documento con el nonbre 'ListaUsuariosSobrePeso' en la direecion /documentos/neatbeans/proyecto con la lista solicitada","Listado");
    }//GEN-LAST:event_SobrePesoButtonActionPerformed

    private void obesidad1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obesidad1ButtonActionPerformed
        ArrayList<Usuario> usuario =new ArrayList<>();
        for(Usuario u: ControladorPersona.uss)
            if("Obesidad clase 1".equals(u.getEstado()))
                usuario.add(u);
        File f = new File("./ListaUsuariosObecidad1.csv");
        try(FileWriter fw = new FileWriter(f)){
            for(Usuario u: usuario)
                fw.write(u.toCSV()+"\n");
        } catch(Exception e){
            mensajeAlerta("No se ha encontrado el docuento","Registro");
        }   
        mensajeAlerta("Se ha creado un documento con el nonbre 'ListaUsuariosObecidad1' en la direecion /documentos/neatbeans/proyecto con la lista solicitada","Listado");
    }//GEN-LAST:event_obesidad1ButtonActionPerformed

    private void obesidad2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obesidad2ButtonActionPerformed
        ArrayList<Usuario> usuario =new ArrayList<>();
        for(Usuario u: ControladorPersona.uss)
            if("Obesidad clase 2".equals(u.getEstado()))
                usuario.add(u);
        File f = new File("./ListaUsuariosObecidad2.csv");
        try(FileWriter fw = new FileWriter(f)){
            for(Usuario u: usuario)
                fw.write(u.toCSV()+"\n");
        } catch(Exception e){
            mensajeAlerta("No se ha encontrado el docuento","Registro");
        } 
        mensajeAlerta("Se ha creado un documento con el nonbre 'ListaUsuariosObecidad2' en la direecion /documentos/neatbeans/proyecto con la lista solicitada","Listado");        
    }//GEN-LAST:event_obesidad2ButtonActionPerformed

    private void obesidad3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obesidad3ButtonActionPerformed
        ArrayList<Usuario> usuario =new ArrayList<>();
        for(Usuario u: ControladorPersona.uss)
            if("Obesidad clase 3".equals(u.getEstado()))
                usuario.add(u);
        File f = new File("./ListaUsuariosObecidad3.csv");
        try(FileWriter fw = new FileWriter(f)){
            for(Usuario u: usuario)
                fw.write(u.toCSV()+"\n");
        } catch(Exception e){
            mensajeAlerta("No se ha encontrado el docuento","Registro");
        } 
        mensajeAlerta("Se ha creado un documento con el nonbre 'ListaUsuariosObecidad3' en la direecion /documentos/neatbeans/proyecto con la lista solicitada","Listado");        
    }//GEN-LAST:event_obesidad3ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaPorEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaPorEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaPorEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaPorEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaPorEstado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SobrePesoButton;
    private javax.swing.JButton bajoPesoButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton obesidad1Button;
    private javax.swing.JButton obesidad2Button;
    private javax.swing.JButton obesidad3Button;
    private javax.swing.JButton saludableButton;
    // End of variables declaration//GEN-END:variables
}
